# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/DEV-1

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: 
  displayName: build
  jobs:
   - job: build 
     steps:
     - script: dotnet build src/microservicio.dotnet.sln --configuration $(buildConfiguration)
       displayName: 'dotnet build $(buildConfiguration)'

- stage: 
  displayName: test
  jobs:
   - job:
     displayName: unit tests job
     steps:
     - task: DotNetCoreCLI@2
       displayName: Run test unit
       inputs:
         command: test
         project: '**/**/*test*/*.csproj'
         publishTestResults: true
         arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura' 
     - task: PublishCodeCoverageResults@1
       displayName: Coverage
       inputs:
         codeCoverageTool: Cobertura
         summaryFileLocation: '**/*coverage.covertura.xml'

 
- stage: 
  displayName: dockerbuild
  jobs:
   - job: dockerbuild 
     steps: 
     - script: docker build -t microservicio.dotnet -f src/Dockerfile .
       displayName: 'docker build'
