# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/DEV-1

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

 
steps:

- task: SonarCloudPrepare@1
  displayName: Sonar Cloud Prepare
  inputs:
    SonarCloud: 'sonarCloud'
    organization: 'mariovillanuevagutierrez'
    scannerMode: 'MSBuild'
    projectKey: 'mariovillanuevagutierrez_Devops-foundation-v2'
    projectName: 'Devops-foundation-v2'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

- script: dotnet build src/microservicio.dotnet.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*test/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx'

- task: SonarCloudAnalyze@1
  displayName: Run code analysis
     
- task: SonarCloudPublish@1
  displayName: Publish Quality Gate Result
  inputs:
    pollingTimeoutSec: '300'
    
- script: docker build -t microservicio.dotnet -f src/Dockerfile .
  displayName: 'docker build'