# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/DEV-1

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet test src/microservicio.dotnet.test/microservicio.dotnet.test.csproj --collect "Code Coverage"
  displayName: 'dotnet test'

- script: dotnet build src/microservicio.dotnet.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: docker build -t microservicio.dotnet -f src/microservicio.dotnet/Dockerfile .
  displayName: 'docker build'
